#!/usr/bin/env python

import waflib.Utils as Utils


def depends(dep):
    dep('sctrltp')


def options(opt):
    opt.load('compiler_cxx')
    opt.load('gtest')
    opt.load('python')
    opt.load('pytest')


def configure(conf):
    conf.load('compiler_cxx')
    conf.load('python')
    conf.check_python_version()
    conf.check_python_headers()
    conf.load('pytest')

    conf.check(
        uselib_store='PYBIND11',
        mandatory = True,
        compiler='cxx',
        features='cxx pyext',
        header_name='pybind11/pybind11.h',
    )


def build(bld):
    bld.shlib(
        target = 'pysctrltp',
        source = 'pysctrltp.cpp',
        features = 'cxx pyext',
        use = ['hostarq', 'arqstream_obj', 'pybind11'],
        install_path = 'lib',
    )

    bld(
        name = 'pysctrltp_tests',
        tests = bld.path.ant_glob('tests/test-*.py'),
        features = 'use pytest',
        use = 'pysctrltp',
        install_path = '${PREFIX}/bin/tests',
        pythonpath = ['.', 'tests'],
    )
