#!/usr/bin/env python

bld(
    features     = 'c cprogram',
    source       = 'test-libhostarq.c',
    target       = 'test-libhostarq',
    includes     = '.',
    use          = 'hostarq',
    install_path = 'bin/tests'
)

bld(
    features = 'c cprogram',
    source='simpleIF.c',
    target='simpleIF',
    includes = '.',
    use=['RT','sctrl', 'us_sctp_if_obj'],
    install_path='bin',
)
