@Library("jenlib@ebrains-4.0") _

withCcache() {
	wafDefaultPipeline(projects: ["sctrltp"],
	                   setupOptions: "--release-branch=ebrains-4.0",
	                   container: [app: "wafer"],
	                   notificationChannel: "#softies",
	                   enableClangFormat: false,
	                   configureInstallOptions: "--build-profile=ci")

	wafDefaultPipeline(projects: ["sctrltp"],
	                   setupOptions: "--release-branch=ebrains-4.0",
	                   container: [app: "dls-core"],
	                   notificationChannel: "#dls-software",
	                   enableClangFormat: false,
	                   configureInstallOptions: "--build-profile=ci")
}
