@Library("jenlib") _

wafDefaultPipeline(projects: ["sctrltp"],
                   container: [app: "visionary-wafer"],
                   notificationChannel: "#softies",
                   enableClangFormat: false)

wafDefaultPipeline(projects: ["sctrltp"],
                   container: [app: "visionary-dls"],
                   notificationChannel: "#dls-software",
                   enableClangFormat: false)
