@Library("jenlib") _

wafDefaultPipeline(projects: ["sctrltp"],
                   container: [app: "wafer"],
                   notificationChannel: "#softies",
                   enableClangFormat: false)

wafDefaultPipeline(projects: ["sctrltp"],
                   container: [app: "dls-core"],
                   notificationChannel: "#dls-software",
                   enableClangFormat: false)
